#!/bin/sh
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-avoid-bind'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-deprecated-headers'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-loop-convert'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-make-shared'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-make-unique'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-pass-by-value'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-raw-string-literal'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-redundant-void-arg'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-replace-auto-ptr'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-replace-random-shuffle'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-return-braced-init-list'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-shrink-to-fit'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-unary-static-assert'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-use-auto'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-use-bool-literals'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-use-default-member-init'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-use-emplace'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-use-equals-default'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-use-equals-delete'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-use-noexcept'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-use-nullptr'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-use-override'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-use-transparent-functors'
#run-clang-tidy-5.0.py -header-filter='.*' -checks='-*,modernize-use-using'
run-clang-tidy-5.0-patch.py -header-filter='.*' -checks='-*,modernize-*' -export-fixes='fixes.yaml'
